docker-test:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker run --rm "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -h