image: maven:3.6.1-jdk-11

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

maven-verify:
  stage: test
  services:
    - eclipse-mosquitto:1.6 # for mqtt client/server tests
  script:
    - 'mvn $MAVEN_CLI_OPTS verify sonar:sonar'
  after_script:
    - '/bin/bash coverage-jacoco.sh'
  coverage: '/\d+.\d+ \% covered/'
  except:
    - master
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"

maven-deploy:
  stage: deploy
  services:
    - eclipse-mosquitto:1.6 # for mqtt client/server tests
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy sonar:sonar'
  after_script:
    - '/bin/bash coverage-jacoco.sh'
  coverage: '/\d+.\d+ \% covered/'
  only:
    - master
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"

maven-release:
  stage: deploy
  only:
    - /^\d+\.\d+/
  except:
    - branches
    - triggers
  script:
    - mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$CI_COMMIT_TAG
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests

build-dist:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS -DskipTests -pl wot-servient-cli -am package'
    - mkdir -p dist/wot-servient
    - cp -R wot-servient-cli/bin wot-servient-cli/target/lib wot-servient-cli/target/wot-servient-cli-*.jar dist/wot-servient
    - cp wot-servient-cli/target/wot-servient-cli-1.2-SNAPSHOT.jar dist/wot-servient/wot-servient.jar
  artifacts:
    paths:
      - dist/wot-servient
  only:
    - master
