image: maven:3.6.1-jdk-11

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

compile:
    stage: build
    script:
        - mvn $MAVEN_CLI_OPTS compile --update-snapshots

build-dist:
  stage: build
  script:
    - mvn -DskipTests --batch-mode -pl wot-servient-cli -am install dependency:copy-dependencies
    - mkdir -p dist/wot-servient/lib dist/wot-servient/bin
    - cp wot-servient-cli/bin/* dist/wot-servient/bin
    - cp wot-servient-cli/target/dependency/*.jar dist/wot-servient/lib
    - cp wot-servient-cli/target/wot-servient-cli-*.jar dist/wot-servient/lib
  artifacts:
    paths:
      - dist/wot-servient
  only:
    - master

.verify: &verify
  stage: test
  script:
    - sh mvnreplace.sh ${CI_COMMIT_REF_NAME}
    - mvn $MAVEN_CLI_OPTS clean compile test verify site sonar:sonar
    - /bin/bash coverage-jacoco.sh
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"

# Verify merge requests using JDK11
verify:jdk11:
  <<: *verify

deploy:jdk11:
  stage: deploy
  script:
    - if [ ! -f ci_settings.xml ];
      then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
      fi
    - 'mvn $MAVEN_CLI_OPTS deploy'
  only:
    - master
