image: maven:3.6.1-jdk-11

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

maven-verify:
  stage: test
  services:
    - eclipse-mosquitto:1.6 # for mqtt client/server tests
  script:
    - 'mvn $MAVEN_CLI_OPTS verify sonar:sonar'
  after_script:
    - '/bin/bash coverage-jacoco.sh'
  coverage: '/\d+.\d+ \% covered/'
  except:
    - master
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"

maven-deploy:
  stage: deploy
  services:
    - eclipse-mosquitto:1.6 # for mqtt client/server tests
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy sonar:sonar'
    - mv wot-servient-cli/target/wot-servient-*.zip .
  after_script:
    - '/bin/bash coverage-jacoco.sh'
  coverage: '/\d+.\d+ \% covered/'
  only:
    - master
    - /^\d+\.\d+/
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    paths:
      - "wot-servient-*.zip"